// <auto-generated />
namespace Wysnan.EIMOnline.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class SecurityUser : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203210726562_SecurityUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9eN8tsOT49++LLZVks8/Hps4/S47LICJXXeXn+nnjtPAReH9keqc9Twq29fnO9yrlfgJ2ua/roqyav/ZbU9vfKr4MP6KOXdbXK6/b6VX6u7589/Si9G753t/uifc17ByjQb8v23t5H6Yt1WWaTkj44z8om/yhdffrodVvV+ef5Mq+zNp+9zNo2r2l2zmY5D0FJ8Wj16e2o8fDuzh6ocTdbLqs2a2mqe4h30Hx93bT54jU1Xjc3IexDenzXUblPe+KHNqO5rbUX/J2/azu0l7av8zY2TamDL3wxDr+OIWO7dfx3VxjQMOrdAU59/EW2WpHIeJyrn6SvhW1Ptl+/P2cuBMbdaRNhUIut7Ym4IbvIO9+CerP8WVE37dOszSYZpuJktog020hk08tNIhEIkHkJv8uLEfENZ6YDzFHyGQ1uQYzN49RREl6bcWEAr6dZmdURATupyvViOSSkm94O+d6HE37Th/j4bmc8Xep5kqEtO6qjOyWbOLnbxPZuObrDuY+Vi25WxD22kiYfpUSqy2IGlhJajNFg/PoXlSdlQeN1Db7IlsV53rRvqrc5jApx/ddX5VZ5Nc2s/H+zPi9Aghs190bteTs9zB19o1q4q0e+QX0szPPZR7NJRfgLxt+Ixu7z8+O7vvvx+GneFBcOBJyRZT6F8XNATZuz5XllKE8D9TEyTToT80XeZjOi13HdFufZtKWvp3nTkMR9lP5kVq6pyeliks/Oll+u29W6PW6afDEpr/3xPr67uX82SyHOj79c4S9PgL/+EAjNgoaQf7l8si7KmcX7WYShBkCAdZTbCavXLbj+4tpCelEtbwlIyfc0X+VLyMqbfLEqCVjz5fJ1dpkP43YzDUOKPX5aZBd1tvApKJ8Y7s6oZ68L6sB/w/VHfxK7ku979P8EAAD//35yiN9wCwAA"; }
        }
    }
}
