// <auto-generated />
namespace Wysnan.EIMOnline.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class SecurityUser : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201204100723306_SecurityUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9eN8tsOT49++LLZVks8/Hps4/S47LICJXXeXn+nnjtPAReH9keqc9Twq29fnO9yrlfgJ2ua/roqyav/ZbU9vfKr4MP6KOXdbXK6/b6VX6u7589/Si9G753t/uifc17ByjQb8v23t5H6Yt1WWaTkj44z8om/yhdffrodVvV+ef5Mq+zNp+9zNo2r2l2zmY5D0FJ8Wj16e2o8fDuzh6ocTdbLqs2a2mqe4h30Hx93bT54jU1XjcG4SfXbe7j29br/CY4b4gbCMpiZYEUy6ymEYA11nVNPHkN3vjso2fFu3z2Uco/nufLi3ZuKfJF9s58cvBeBDupFqt1C7A/6wTDv2aMr9uaxOzGsdCvH6VfLYspj1+o+X7UfV5dFEvHUT+0fl9ezX6W+3x810lrX4aJedqMdESt+ODv/F3bkWFp+zpvY+KeOviiX8bh1zFkbLdOj90VRWYU3t0Bjff4i2y1Ijp5GlA/SV+L+jvZfv3+Gm4hMO5Om4iis9jankhIsou88y2oN8ufFXXTPs3abJJh5k5mi0izjUQ2vdykWgNFbF7C7/JixAyEM9MB5ij5jAa3IAXJ49RREl6bcWEAr6dZmdURRX1SlevFckjZb3o71J8+nPCb20P0NKkPzvv49rBEWflg5JPbQ7CaxwdiP7w9HNYkPgz+oP/+47udWe7ylKcvtGXHMHcZdZN8d5vY3q2cd+T5scrWzW5OT9ikyUcpEeaymEHQhEPGaDB+/YvKk7Kg8boGX2TL4jxv2jfV2xwuG+mCr+8oWUvXNLPy/83eUgES3OgX9XyD9/dy2mJ5zZ29n0nsOTp1daXu9yDezj15T7x9Z2N5mdXTeVZvLbJ3d94X644D8UGwPKfgPeC8r6HvmqoBa/R1TL5I4mcfzSYVDUQQ/kacgr5yeHzXj5QeP82b4sKBQNy0zKdwOx1Q0+ZseV4ZytNAfYxMk87EfJG32YzodVy3xXk2benrad407Lb9ZFauqcnpYpLPzpZfrltiyOOmyReT8tof7+O7m/tnzyfE+fGXK/zlacOvPwRCs6Ah5F8un6yLcmbxftaXliEQYB0VQcKK3FYCd3FtIb2olrcEpOR7mq/yJRTPm3yxKglY8+XydXaZD+N2Mw1Dij1+WmQXdbbwKSifGO4mdVN6XVAH/huuP/qT2JXC9KP/JwAA//9yJLvaGxAAAA=="; }
        }
    }
}
