// <auto-generated />
namespace Wysnan.EIMOnline.EF.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class SecurityUser : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201203211128252_SecurityUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAOy9B2AcSZYlJi9tynt/SvVK1+B0oQiAYBMk2JBAEOzBiM3mkuwdaUcjKasqgcplVmVdZhZAzO2dvPfee++999577733ujudTif33/8/XGZkAWz2zkrayZ4hgKrIHz9+fB8/Iv7Hv/cffPx7vFuU6WVeN0W1/Oyj3fHOR2m+nFazYnnx2Ufr9nz74KPf4+g3Th6fzhbv0p807fbQjt5cNp99NG/b1aO7d5vpPF9kzXhRTOuqqc7b8bRa3M1m1d29nZ2Du7s7d3MC8RHBStPHr9bLtljk/Af9eVItp/mqXWflF9UsLxv9nL55zVDTF9kib1bZNP/so+9eN8tsOT49++LLZVks8/Hps4/S47LICJXXeXn+nnjtPAReH9keqc9Twq29fnO9yrlfgJ2ua/roqyav/ZbU9vfKr4MP6KOXdbXK6/b6VX6u7589/Si9G753t/uifc17ByjQb8v23t5H6Yt1WWaTkj44z8om/yhdffrodVvV+ef5Mq+zNp+9zNo2r2l2zmY5D0FJ8Wj16e2o8fDuzh6ocTdbLqs2a2mqe4h30Hx93bT54jU1Xjc3IbwZ0hviB4KzWBkwT4plVtMYwBzruiauvAZ3fPbRs+JdPvso5R/P8+VFO7ddfJG9M58cvBfJTqrFat0C7M86yfCvGePrtiZBu3Es9OtH6VfLYsrjb+t17g9O/t7c6fPqolg6nvqh9fvyavaz3Ofju05e+1JMzNNmpCVqxQd/5+/ajhRL29d5GxP41MEXDTMOv44hY7t1muyuqDKj8u4O6LzHX2SrFdHJ04H6SfpaFODJ9uv313ELgXF32kRUncXW9kRCkl3knW9BvVn+rKib9mnWZpMMM3cyW0SabSSy6eUm5RqoYvMSfpcXI4YgnJkOMEfJZzS4BalIHqeOkvDajAsDeD3NyqyOqOqTqlwvlkPqftPboQb14YTf3B6ip0l9cN7Ht4clysoHI5/cHoLVPD4Q++Ht4bAm8WHwB/33H9/tzHKXpzx9oS07prnLqJvku9vE9m7lvCPPj1W2bnZ0esImTT5KiTCXxQyCJhwyRoPx619UnpQFjdc1+CJbFud5076p3uZw2kgXfH1XyVq6ppmV/2/2lwqQ4EbP6D29k5ifwx29J5yel1NXV+p9DyLtfJP37Mz3NJaXWT2dZ/XWInt3532teMd7+CBYnkfwHnDe18p37dSAKfo69l7E8LOPZpOKBiIIfyMeQV8zPL7rB0qPn+ZNceFAIGxa5lP4nA6oaXO2PK8M5WmgPkamSWdivsjbbEb0Oq7b4jybtvT1NG8a9tl+MivX1OR0MclnZ8sv1y0x5HHT5ItJee2P9/Hdzf2z2xPi/PjLFf7yVOHXHwKhWdAQ8i+XT9ZFObN4P+tLyxAIsI6KIGFFPiuBu7i2kF5Uy1sCUvI9zVf5ElrnTb5YlQSs+XL5OrvMh3G7mYYhxR4/LbKLOlv4FJRPDHeTuim9LqgD/w3XH/1J7EpR+tH/EwAA//8LDOGRGhAAAA=="; }
        }
    }
}
