<?xml version="1.0" encoding="utf-8"?><Database Name="EimOnlineDB" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WANGYONGGUI-PC;Initial Catalog=EimOnlineDB;Persist Security Info=True;User ID=wangyonggui" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="EimOnlineDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.T_Student" Member="T_Students">
    <Type Name="T_Student">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.T_Student2" Member="T_Student2s">
    <Type Name="T_Student2">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>